version: '3'

networks:
  cloud_network:

services:
  # Start the Eureka server
  eureka-server:
    container_name: eureka-container
    restart: on-failure
    build:
      context: ./
      dockerfile: BuildEurekaImage
    expose:
      - 6001
    ports:
      - 8761:8761
      - 6001:6001    
    networks:
      - cloud_network