version: '3'

networks:
  cloud_network:
    driver: bridge
  
volumes:
  zipkin_data:
    driver: local

services:    
  ###################################
  #       EDGE MICROSERVICES        #
  ###################################
  
  # Start the Eureka server
  eureka-server:
    container_name: eureka-container
    restart: on-failure
    build:
      context: eureka-server
      dockerfile: BuildEurekaImage
    expose:
      - 6001
    ports:
      - 8761:8761
      - 6001:6001    
    networks:
      - cloud_network
  
  # Start the Config server
  config-server:
    container_name: config-container
    restart: on-failure
    build:
      context: config-server
      dockerfile: BuildConfigImage
    environment:
      EUREKA_SERVER_URL: http://eureka-server:6001/eureka
    expose:
      - 6000
    ports:
      - 8888:8888
      - 6000:6000  
    networks:
      - cloud_network
    depends_on:
      - eureka-server
  
  # Start the cloud gateway
  gateway-service:
    container_name: gateway-container
    restart: on-failure
    build:
      context: cloud-gateway
      dockerfile: BuildGatewayImage
    environment:
      EUREKA_SERVER_URL: http://eureka-server:6001/eureka 
      CONFIG_SERVER_BASE_URL: http://config-server:6000
      ZIPKIN_BASE_URL: http://zipkin-service:9411
    expose:
      - 6002
    ports:
      - 8989:8989
      - 6002:6002    
    networks:
      - cloud_network
    depends_on:
      - eureka-server
      - config-server
  
  # Start the Zipkin server
  zipkin-service:
    image: openzipkin/zipkin
    container_name: zipkin-container
    restart: on-failure
    volumes:
      - zipkin_data:/var/lib/zipkin
    ports:
      - 9411:9411    
    networks:
      - cloud_network
  
  ###################################
  #         MICROSERVICES           #
  ###################################
  # Start clientui service
  clientui-service:
    container_name: clientui-container
    restart: on-failure
    build:
      context: clientui-service
      dockerfile: BuildClientUIImage
    expose:
      - 7000
    ports:
      - 7000:7000
    networks:
      - cloud_network
    depends_on:
      - eureka-server
      - config-server
      - gateway-service
  
  # Start the product-service
  product-service:
    container_name: product-container
    restart: on-failure
    build:
      context: product-service
      dockerfile: BuildProductImage
    expose:
      - 7001
    ports:
      - 7001:7001
    environment:
      WAIT_HOSTS: mysql:3306
    networks:
      - cloud_network
    depends_on:
      - eureka-server
      - config-server
      - gateway-service
      
  # Start the order-service
  order-service:
    container_name: order-container
    restart: on-failure
    build:
      context: order-service
      dockerfile: BuildOrderImage
    expose:
      - 7002
    ports:
      - 7002:7002
    environment:
      WAIT_HOSTS: mysql:3306
    networks:
      - cloud_network
    depends_on:
      - eureka-server
      - config-server
      - gateway-service
      
  # Start the payment-service
  payment-service:
    container_name: payment-container
    restart: on-failure
    build:
      context: payment-service
      dockerfile: BuildPaymentImage
    expose:
      - 7003
    ports:
      - 7003:7003
    environment:
      WAIT_HOSTS: mysql:3306
    networks:
      - cloud_network
    depends_on:
      - eureka-server
      - config-server
      - gateway-service
      
  # Start the mail-service
  mail-service:
    container_name: mail-container
    restart: on-failure
    build:
      context: mail-server
      dockerfile: BuildMailImage
    expose:
      - 7005
    ports:
      - 7005:7005
    networks:
      - cloud_network
    depends_on:
      - eureka-server
      - config-server
      - gateway-service