version: '3'
networks:
   docker_network:
      ipam:
         config:
            - subnet: 172.18.0.0/16
services:
  docker-mysqldb:
    restart: always
    container_name: userdb-container
    #image: mariadb
    image: mysql
    environment:
      MYSQL_DATABASE: userdb
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "3307:3307"
    #networks:
       #docker_network:
          #ipv4_address: 172.18.0.10

    healthcheck:
      test: "/usr/bin/mysql --user=root --password=admin --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
  docker-spring-app:
    container_name: user-app-container
    restart: on-failure
    build: ./
    expose:
      - "8090/tcp"
    ports:
      - 8080:8080
      - 8090:8090
    #networks:
       #docker_network:
          #ipv4_address: 172.18.0.11
    environment:
            #WAIT_HOSTS: mariadb:3306
            WAIT_HOSTS: mariadb:3306
    depends_on:
            - docker-mysqldb
