server:
  port: 6003

eureka:
  client:
    register-with-eureka: true
    feth-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://127.0.0.1:6001/eureka}
    instance:
      hostname: localhost

spring:
  zipkin:
    base-url: ${ZIPKIN_BASE_URL:http://127.0.0.1:9411}
  cloud:
    gateway:
      httpclient:
        connect-timeout: 100000
        response-timeout: 100000
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payments/**